/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICryptoDevsNFT,
  ICryptoDevsNFTInterface,
} from "../ICryptoDevsNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "tokenOfOwnerByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICryptoDevsNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ICryptoDevsNFTInterface {
    return new utils.Interface(_abi) as ICryptoDevsNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICryptoDevsNFT {
    return new Contract(address, _abi, signerOrProvider) as ICryptoDevsNFT;
  }
}
